"""Create all application tables

Revision ID: 22d4bdcb1bbf
Revises: 
Create Date: 2025-11-04 09:23:22.705404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22d4bdcb1bbf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_performance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=255), nullable=False),
    sa.Column('total_executions', sa.Float(), nullable=True),
    sa.Column('accepted_count', sa.Float(), nullable=True),
    sa.Column('rejected_count', sa.Float(), nullable=True),
    sa.Column('modified_count', sa.Float(), nullable=True),
    sa.Column('acceptance_rate', sa.Float(), nullable=True),
    sa.Column('average_confidence', sa.Float(), nullable=True),
    sa.Column('average_user_rating', sa.Float(), nullable=True),
    sa.Column('trend', sa.String(length=50), nullable=True),
    sa.Column('last_improvement_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_performance_agent_name'), 'agent_performance', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_performance_project_id'), 'agent_performance', ['project_id'], unique=False)
    op.create_table('ai_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=255), nullable=False),
    sa.Column('agent_type', sa.String(length=255), nullable=True),
    sa.Column('feedback_type', sa.Enum('ACCEPTED', 'REJECTED', 'MODIFIED', 'RATING', name='feedbacktype'), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=False),
    sa.Column('user_feedback', sa.JSON(), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('user_rating', sa.Float(), nullable=True),
    sa.Column('modifications', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('qdrant_point_id', sa.String(length=255), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_feedback_agent_name'), 'ai_feedback', ['agent_name'], unique=False)
    op.create_index(op.f('ix_ai_feedback_created_at'), 'ai_feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_feedback_is_accepted'), 'ai_feedback', ['is_accepted'], unique=False)
    op.create_index(op.f('ix_ai_feedback_project_id'), 'ai_feedback', ['project_id'], unique=False)
    op.create_table('api_collections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requests', sa.JSON(), nullable=True),
    sa.Column('environment', sa.JSON(), nullable=True),
    sa.Column('imported_from', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_knowledge',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('document_name', sa.String(length=500), nullable=True),
    sa.Column('document_type', sa.Enum('DESCRIPTION', 'REQUIREMENT', 'SPECIFICATION', 'TEST_PLAN', 'TEST_CASE', 'DOCUMENT', 'CODE', 'DATA', 'METADATA', 'OTHER', name='documenttype'), nullable=True),
    sa.Column('source', sa.Enum('TEXT_INPUT', 'FILE_UPLOAD', 'STRUCTURED_DATA', 'API_REQUEST', 'REQUIREMENT', 'SPECIFICATION', 'TEST_PLAN', 'TEST_CASE', name='documentsource'), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_preview', sa.String(length=1000), nullable=True),
    sa.Column('content_length', sa.Integer(), nullable=True),
    sa.Column('total_chunks', sa.Integer(), nullable=True),
    sa.Column('chunk_hashes', sa.JSON(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('times_used_in_generation', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('learning_contribution', sa.Float(), nullable=True),
    sa.Column('qdrant_collection', sa.String(length=255), nullable=True),
    sa.Column('qdrant_point_ids', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('is_indexed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_knowledge_created_at'), 'document_knowledge', ['created_at'], unique=False)
    op.create_index(op.f('ix_document_knowledge_document_type'), 'document_knowledge', ['document_type'], unique=False)
    op.create_index(op.f('ix_document_knowledge_is_active'), 'document_knowledge', ['is_active'], unique=False)
    op.create_index(op.f('ix_document_knowledge_project_id'), 'document_knowledge', ['project_id'], unique=False)
    op.create_index(op.f('ix_document_knowledge_source'), 'document_knowledge', ['source'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_length', sa.Integer(), nullable=False),
    sa.Column('qdrant_point_id', sa.String(length=255), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.Column('effectiveness_score', sa.Float(), nullable=True),
    sa.Column('user_rating', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document_knowledge.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qdrant_point_id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_table('document_usage_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=True),
    sa.Column('agent_name', sa.String(length=255), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('generation_id', sa.String(length=255), nullable=True),
    sa.Column('was_useful', sa.Integer(), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document_knowledge.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_usage_log_agent_name'), 'document_usage_log', ['agent_name'], unique=False)
    op.create_index(op.f('ix_document_usage_log_document_id'), 'document_usage_log', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_usage_log_project_id'), 'document_usage_log', ['project_id'], unique=False)
    op.create_index(op.f('ix_document_usage_log_used_at'), 'document_usage_log', ['used_at'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('related_test_case_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='issueseverity'), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'WONT_FIX', name='issuestatus'), nullable=True),
    sa.Column('detected_by', sa.Enum('AI', 'MANUAL', 'AUTOMATION', name='issuedetectedby'), nullable=True),
    sa.Column('remediation_suggestions', sa.JSON(), nullable=True),
    sa.Column('ai_confidence', sa.String(length=50), nullable=True),
    sa.Column('steps_to_reproduce', sa.JSON(), nullable=True),
    sa.Column('environment', sa.JSON(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_test_case_id'], ['test_cases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('idx_user_projects_project_id'), table_name='user_projects')
    op.drop_index(op.f('idx_user_projects_user_id'), table_name='user_projects')
    op.drop_table('user_projects')
    op.drop_index(op.f('idx_groups_group_type_id'), table_name='groups')
    op.drop_index(op.f('idx_oauth_accounts_created_at'), table_name='oauth_accounts')
    op.drop_index(op.f('idx_oauth_accounts_provider'), table_name='oauth_accounts')
    op.drop_index(op.f('idx_oauth_accounts_user_id'), table_name='oauth_accounts')
    op.drop_constraint(op.f('oauth_accounts_provider_provider_user_id_key'), 'oauth_accounts', type_='unique')
    op.create_index(op.f('ix_oauth_accounts_created_at'), 'oauth_accounts', ['created_at'], unique=False)
    op.create_index(op.f('ix_oauth_accounts_id'), 'oauth_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_oauth_accounts_user_id'), 'oauth_accounts', ['user_id'], unique=False)
    op.drop_constraint(op.f('oauth_accounts_user_id_fkey'), 'oauth_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'oauth_accounts', 'users', ['user_id'], ['id'])
    op.alter_column('user_organisations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_user_organisations_org_id'), table_name='user_organisations')
    op.drop_index(op.f('idx_user_organisations_user_id'), table_name='user_organisations')
    op.create_index(op.f('ix_user_organisations_organisation_id'), 'user_organisations', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_user_organisations_user_id'), 'user_organisations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_organisations_user_id'), table_name='user_organisations')
    op.drop_index(op.f('ix_user_organisations_organisation_id'), table_name='user_organisations')
    op.create_index(op.f('idx_user_organisations_user_id'), 'user_organisations', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_organisations_org_id'), 'user_organisations', ['organisation_id'], unique=False)
    op.alter_column('user_organisations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'oauth_accounts', type_='foreignkey')
    op.create_foreign_key(op.f('oauth_accounts_user_id_fkey'), 'oauth_accounts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_oauth_accounts_user_id'), table_name='oauth_accounts')
    op.drop_index(op.f('ix_oauth_accounts_id'), table_name='oauth_accounts')
    op.drop_index(op.f('ix_oauth_accounts_created_at'), table_name='oauth_accounts')
    op.create_unique_constraint(op.f('oauth_accounts_provider_provider_user_id_key'), 'oauth_accounts', ['provider', 'provider_user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_oauth_accounts_user_id'), 'oauth_accounts', ['user_id'], unique=False)
    op.create_index(op.f('idx_oauth_accounts_provider'), 'oauth_accounts', ['provider'], unique=False)
    op.create_index(op.f('idx_oauth_accounts_created_at'), 'oauth_accounts', ['created_at'], unique=False)
    op.create_index(op.f('idx_groups_group_type_id'), 'groups', ['group_type_id'], unique=False)
    op.create_table('user_projects',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), server_default=sa.text("'member'::character varying"), autoincrement=False, nullable=False),
    sa.Column('assigned_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('user_projects_assigned_by_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('user_projects_project_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_projects_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'project_id', name=op.f('user_projects_pkey'))
    )
    op.create_index(op.f('idx_user_projects_user_id'), 'user_projects', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_projects_project_id'), 'user_projects', ['project_id'], unique=False)
    op.drop_table('issues')
    op.drop_index(op.f('ix_document_usage_log_used_at'), table_name='document_usage_log')
    op.drop_index(op.f('ix_document_usage_log_project_id'), table_name='document_usage_log')
    op.drop_index(op.f('ix_document_usage_log_document_id'), table_name='document_usage_log')
    op.drop_index(op.f('ix_document_usage_log_agent_name'), table_name='document_usage_log')
    op.drop_table('document_usage_log')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_document_knowledge_source'), table_name='document_knowledge')
    op.drop_index(op.f('ix_document_knowledge_project_id'), table_name='document_knowledge')
    op.drop_index(op.f('ix_document_knowledge_is_active'), table_name='document_knowledge')
    op.drop_index(op.f('ix_document_knowledge_document_type'), table_name='document_knowledge')
    op.drop_index(op.f('ix_document_knowledge_created_at'), table_name='document_knowledge')
    op.drop_table('document_knowledge')
    op.drop_table('api_collections')
    op.drop_index(op.f('ix_ai_feedback_project_id'), table_name='ai_feedback')
    op.drop_index(op.f('ix_ai_feedback_is_accepted'), table_name='ai_feedback')
    op.drop_index(op.f('ix_ai_feedback_created_at'), table_name='ai_feedback')
    op.drop_index(op.f('ix_ai_feedback_agent_name'), table_name='ai_feedback')
    op.drop_table('ai_feedback')
    op.drop_index(op.f('ix_agent_performance_project_id'), table_name='agent_performance')
    op.drop_index(op.f('ix_agent_performance_agent_name'), table_name='agent_performance')
    op.drop_table('agent_performance')
    # ### end Alembic commands ###
