"""Enhance issues model with comprehensive defect lifecycle

Revision ID: 35102c946304
Revises: ieee829_001
Create Date: 2025-11-06 08:54:49.096306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35102c946304'
down_revision: Union[str, Sequence[str], None] = 'ieee829_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_performance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=255), nullable=False),
    sa.Column('total_executions', sa.Float(), nullable=True),
    sa.Column('accepted_count', sa.Float(), nullable=True),
    sa.Column('rejected_count', sa.Float(), nullable=True),
    sa.Column('modified_count', sa.Float(), nullable=True),
    sa.Column('acceptance_rate', sa.Float(), nullable=True),
    sa.Column('average_confidence', sa.Float(), nullable=True),
    sa.Column('average_user_rating', sa.Float(), nullable=True),
    sa.Column('trend', sa.String(length=50), nullable=True),
    sa.Column('last_improvement_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_performance_agent_name'), 'agent_performance', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_performance_project_id'), 'agent_performance', ['project_id'], unique=False)
    op.create_table('ai_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=255), nullable=False),
    sa.Column('agent_type', sa.String(length=255), nullable=True),
    sa.Column('feedback_type', sa.Enum('ACCEPTED', 'REJECTED', 'MODIFIED', 'RATING', name='feedbacktype'), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=False),
    sa.Column('user_feedback', sa.JSON(), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('user_rating', sa.Float(), nullable=True),
    sa.Column('modifications', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('qdrant_point_id', sa.String(length=255), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_feedback_agent_name'), 'ai_feedback', ['agent_name'], unique=False)
    op.create_index(op.f('ix_ai_feedback_created_at'), 'ai_feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_feedback_is_accepted'), 'ai_feedback', ['is_accepted'], unique=False)
    op.create_index(op.f('ix_ai_feedback_project_id'), 'ai_feedback', ['project_id'], unique=False)
    op.create_table('api_collections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requests', sa.JSON(), nullable=True),
    sa.Column('environment', sa.JSON(), nullable=True),
    sa.Column('imported_from', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_knowledge',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('document_name', sa.String(length=500), nullable=True),
    sa.Column('document_type', sa.Enum('DESCRIPTION', 'REQUIREMENT', 'SPECIFICATION', 'TEST_PLAN', 'TEST_CASE', 'DOCUMENT', 'CODE', 'DATA', 'METADATA', 'OTHER', name='documenttype'), nullable=True),
    sa.Column('source', sa.Enum('TEXT_INPUT', 'FILE_UPLOAD', 'STRUCTURED_DATA', 'API_REQUEST', 'REQUIREMENT', 'SPECIFICATION', 'TEST_PLAN', 'TEST_CASE', name='documentsource'), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_preview', sa.String(length=1000), nullable=True),
    sa.Column('content_length', sa.Integer(), nullable=True),
    sa.Column('total_chunks', sa.Integer(), nullable=True),
    sa.Column('chunk_hashes', sa.JSON(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('times_used_in_generation', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('learning_contribution', sa.Float(), nullable=True),
    sa.Column('qdrant_collection', sa.String(length=255), nullable=True),
    sa.Column('qdrant_point_ids', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('is_indexed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_knowledge_created_at'), 'document_knowledge', ['created_at'], unique=False)
    op.create_index(op.f('ix_document_knowledge_document_type'), 'document_knowledge', ['document_type'], unique=False)
    op.create_index(op.f('ix_document_knowledge_is_active'), 'document_knowledge', ['is_active'], unique=False)
    op.create_index(op.f('ix_document_knowledge_project_id'), 'document_knowledge', ['project_id'], unique=False)
    op.create_index(op.f('ix_document_knowledge_source'), 'document_knowledge', ['source'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_length', sa.Integer(), nullable=False),
    sa.Column('qdrant_point_id', sa.String(length=255), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.Column('effectiveness_score', sa.Float(), nullable=True),
    sa.Column('user_rating', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document_knowledge.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qdrant_point_id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_table('document_usage_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=True),
    sa.Column('agent_name', sa.String(length=255), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('generation_id', sa.String(length=255), nullable=True),
    sa.Column('was_useful', sa.Integer(), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document_knowledge.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_usage_log_agent_name'), 'document_usage_log', ['agent_name'], unique=False)
    op.create_index(op.f('ix_document_usage_log_document_id'), 'document_usage_log', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_usage_log_project_id'), 'document_usage_log', ['project_id'], unique=False)
    op.create_index(op.f('ix_document_usage_log_used_at'), 'document_usage_log', ['used_at'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('related_test_case_id', sa.UUID(), nullable=True),
    sa.Column('test_run_id', sa.UUID(), nullable=True),
    sa.Column('test_plan_id', sa.UUID(), nullable=True),
    sa.Column('external_issue_key', sa.String(length=255), nullable=True),
    sa.Column('external_system', sa.String(length=100), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='issueseverity'), nullable=True),
    sa.Column('priority', sa.Enum('TRIVIAL', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', 'BLOCKER', name='issuepriority'), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'ASSIGNED', 'IN_PROGRESS', 'FIXED', 'RETESTED', 'CLOSED', 'REOPENED', 'WONT_FIX', 'DUPLICATE', 'DEFERRED', name='issuestatus'), nullable=True),
    sa.Column('detected_by', sa.Enum('AI', 'MANUAL', 'AUTOMATION', name='issuedetectedby'), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('assigned_to_name', sa.String(length=255), nullable=True),
    sa.Column('reporter_id', sa.UUID(), nullable=True),
    sa.Column('resolution', sa.String(length=255), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('fixed_in_version', sa.String(length=100), nullable=True),
    sa.Column('remediation_suggestions', sa.JSON(), nullable=True),
    sa.Column('ai_confidence', sa.String(length=50), nullable=True),
    sa.Column('root_cause_analysis', sa.Text(), nullable=True),
    sa.Column('steps_to_reproduce', sa.JSON(), nullable=True),
    sa.Column('actual_result', sa.Text(), nullable=True),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('environment', sa.JSON(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('affected_features', sa.JSON(), nullable=True),
    sa.Column('affected_users', sa.String(length=255), nullable=True),
    sa.Column('workaround', sa.Text(), nullable=True),
    sa.Column('comments', sa.JSON(), nullable=True),
    sa.Column('status_history', sa.JSON(), nullable=True),
    sa.Column('estimated_effort_hours', sa.String(length=50), nullable=True),
    sa.Column('actual_effort_hours', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_test_case_id'], ['test_cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_plan_id'], ['test_plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_priority'), 'issues', ['priority'], unique=False)
    op.create_index(op.f('ix_issues_severity'), 'issues', ['severity'], unique=False)
    op.create_index(op.f('ix_issues_status'), 'issues', ['status'], unique=False)
    op.create_index(op.f('ix_issues_title'), 'issues', ['title'], unique=False)
    op.drop_constraint('group_type_access_organization_id_fkey', 'group_type_access', type_='foreignkey')
    op.create_foreign_key(None, 'group_type_access', 'organisations', ['organization_id'], ['id'])
    op.drop_constraint('group_types_organization_id_fkey', 'group_types', type_='foreignkey')
    op.create_foreign_key(None, 'group_types', 'organisations', ['organization_id'], ['id'])
    op.add_column('groups', sa.Column('group_type_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'groups', 'group_types', ['group_type_id'], ['id'])
    op.drop_constraint('projects_organisation_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'organisations', ['organisation_id'], ['id'])
    op.alter_column('test_plans', 'test_objectives_ieee',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='IEEE 829 Test Objectives with success criteria and quality goals',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('test_plans', 'scope_of_testing_ieee',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='IEEE 829 Scope of Testing with in-scope, out-of-scope, features, systems, environments',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('test_plans', 'test_approach_ieee',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='IEEE 829 Test Approach with methodology, testing types, techniques, automation approach',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('test_plans', 'assumptions_constraints_ieee',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='IEEE 829 Assumptions and Constraints with type, description, impact, mitigation',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('test_plans', 'test_schedule_ieee',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='IEEE 829 Test Schedule with phases, milestones, dependencies, critical path',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('test_plans', 'resources_roles_ieee',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='IEEE 829 Resources and Roles with responsibilities, skills, allocation',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('test_plans', 'test_environment_ieee',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='IEEE 829 Test Environment with environments, hardware, software, network, test data',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('test_plans', 'entry_exit_criteria_ieee',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='IEEE 829 Entry/Exit Criteria with entry, exit, suspension, resumption criteria',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('test_plans', 'risk_management_ieee',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='IEEE 829 Risk Management with risks, mitigation, contingency plans, risk matrix',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('test_plans', 'deliverables_reporting_ieee',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='IEEE 829 Deliverables and Reporting with deliverables, reporting structure, communication plan, metrics',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('test_plans', 'approval_signoff_ieee',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='IEEE 829 Approval and Sign-off with approvers, criteria, process, escalation matrix',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_plans', 'approval_signoff_ieee',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='IEEE 829 Approval and Sign-off with approvers, criteria, process, escalation matrix',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('test_plans', 'deliverables_reporting_ieee',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='IEEE 829 Deliverables and Reporting with deliverables, reporting structure, communication plan, metrics',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('test_plans', 'risk_management_ieee',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='IEEE 829 Risk Management with risks, mitigation, contingency plans, risk matrix',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('test_plans', 'entry_exit_criteria_ieee',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='IEEE 829 Entry/Exit Criteria with entry, exit, suspension, resumption criteria',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('test_plans', 'test_environment_ieee',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='IEEE 829 Test Environment with environments, hardware, software, network, test data',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('test_plans', 'resources_roles_ieee',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='IEEE 829 Resources and Roles with responsibilities, skills, allocation',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('test_plans', 'test_schedule_ieee',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='IEEE 829 Test Schedule with phases, milestones, dependencies, critical path',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('test_plans', 'assumptions_constraints_ieee',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='IEEE 829 Assumptions and Constraints with type, description, impact, mitigation',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('test_plans', 'test_approach_ieee',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='IEEE 829 Test Approach with methodology, testing types, techniques, automation approach',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('test_plans', 'scope_of_testing_ieee',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='IEEE 829 Scope of Testing with in-scope, out-of-scope, features, systems, environments',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('test_plans', 'test_objectives_ieee',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='IEEE 829 Test Objectives with success criteria and quality goals',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_organisation_id_fkey', 'projects', 'organisations', ['organisation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'group_type_id')
    op.drop_constraint(None, 'group_types', type_='foreignkey')
    op.create_foreign_key('group_types_organization_id_fkey', 'group_types', 'organisations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'group_type_access', type_='foreignkey')
    op.create_foreign_key('group_type_access_organization_id_fkey', 'group_type_access', 'organisations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_issues_title'), table_name='issues')
    op.drop_index(op.f('ix_issues_status'), table_name='issues')
    op.drop_index(op.f('ix_issues_severity'), table_name='issues')
    op.drop_index(op.f('ix_issues_priority'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('ix_document_usage_log_used_at'), table_name='document_usage_log')
    op.drop_index(op.f('ix_document_usage_log_project_id'), table_name='document_usage_log')
    op.drop_index(op.f('ix_document_usage_log_document_id'), table_name='document_usage_log')
    op.drop_index(op.f('ix_document_usage_log_agent_name'), table_name='document_usage_log')
    op.drop_table('document_usage_log')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_document_knowledge_source'), table_name='document_knowledge')
    op.drop_index(op.f('ix_document_knowledge_project_id'), table_name='document_knowledge')
    op.drop_index(op.f('ix_document_knowledge_is_active'), table_name='document_knowledge')
    op.drop_index(op.f('ix_document_knowledge_document_type'), table_name='document_knowledge')
    op.drop_index(op.f('ix_document_knowledge_created_at'), table_name='document_knowledge')
    op.drop_table('document_knowledge')
    op.drop_table('api_collections')
    op.drop_index(op.f('ix_ai_feedback_project_id'), table_name='ai_feedback')
    op.drop_index(op.f('ix_ai_feedback_is_accepted'), table_name='ai_feedback')
    op.drop_index(op.f('ix_ai_feedback_created_at'), table_name='ai_feedback')
    op.drop_index(op.f('ix_ai_feedback_agent_name'), table_name='ai_feedback')
    op.drop_table('ai_feedback')
    op.drop_index(op.f('ix_agent_performance_project_id'), table_name='agent_performance')
    op.drop_index(op.f('ix_agent_performance_agent_name'), table_name='agent_performance')
    op.drop_table('agent_performance')
    # ### end Alembic commands ###
