"""add_performance_testing_tables

Revision ID: 721756dbd280
Revises: security_advanced_001
Create Date: 2026-01-03 12:36:03.837566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '721756dbd280'
down_revision: Union[str, Sequence[str], None] = 'security_advanced_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_tests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('human_id', sa.String(length=15), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('test_type', sa.Enum('lighthouse', 'load', 'stress', 'spike', 'endurance', 'api', name='testtype'), nullable=False),
    sa.Column('target_url', sa.String(length=2000), nullable=False),
    sa.Column('target_method', sa.String(length=10), nullable=True),
    sa.Column('target_headers', sa.JSON(), nullable=True),
    sa.Column('target_body', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'queued', 'running', 'completed', 'failed', 'cancelled', name='teststatus'), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('provider', sa.Enum('pagespeed_insights', 'webpagetest', 'gtmetrix', 'loader_io', 'k6_cloud', 'artillery', name='testprovider'), nullable=True),
    sa.Column('provider_test_id', sa.String(length=255), nullable=True),
    sa.Column('device_type', sa.Enum('mobile', 'desktop', name='devicetype'), nullable=True),
    sa.Column('connection_type', sa.Enum('cable', 'dsl', 'slow_3g', 'fast_3g', 'lte', 'no_throttle', name='connectiontype'), nullable=True),
    sa.Column('test_location', sa.String(length=100), nullable=True),
    sa.Column('virtual_users', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('ramp_up_seconds', sa.Integer(), nullable=True),
    sa.Column('ramp_down_seconds', sa.Integer(), nullable=True),
    sa.Column('load_profile', sa.Enum('constant', 'ramp_up', 'ramp_down', 'spike', 'step', 'custom', name='loadprofile'), nullable=True),
    sa.Column('stages', sa.JSON(), nullable=True),
    sa.Column('thresholds', sa.JSON(), nullable=True),
    sa.Column('threshold_passed', sa.Boolean(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.Column('ai_recommendations', sa.JSON(), nullable=True),
    sa.Column('ai_risk_level', sa.String(length=20), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.UUID(), nullable=True),
    sa.Column('trigger_source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('human_id')
    )
    op.create_index('ix_performance_tests_created_at', 'performance_tests', ['created_at'], unique=False)
    op.create_index('ix_performance_tests_organisation_id', 'performance_tests', ['organisation_id'], unique=False)
    op.create_index('ix_performance_tests_project_id', 'performance_tests', ['project_id'], unique=False)
    op.create_index('ix_performance_tests_status', 'performance_tests', ['status'], unique=False)
    op.create_index('ix_performance_tests_test_type', 'performance_tests', ['test_type'], unique=False)
    op.create_table('performance_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('accessibility_score', sa.Float(), nullable=True),
    sa.Column('seo_score', sa.Float(), nullable=True),
    sa.Column('best_practices_score', sa.Float(), nullable=True),
    sa.Column('pwa_score', sa.Float(), nullable=True),
    sa.Column('largest_contentful_paint', sa.Float(), nullable=True),
    sa.Column('first_input_delay', sa.Float(), nullable=True),
    sa.Column('cumulative_layout_shift', sa.Float(), nullable=True),
    sa.Column('first_contentful_paint', sa.Float(), nullable=True),
    sa.Column('time_to_first_byte', sa.Float(), nullable=True),
    sa.Column('speed_index', sa.Float(), nullable=True),
    sa.Column('time_to_interactive', sa.Float(), nullable=True),
    sa.Column('total_blocking_time', sa.Float(), nullable=True),
    sa.Column('total_byte_weight', sa.Integer(), nullable=True),
    sa.Column('total_requests', sa.Integer(), nullable=True),
    sa.Column('dom_size', sa.Integer(), nullable=True),
    sa.Column('opportunities', sa.JSON(), nullable=True),
    sa.Column('diagnostics', sa.JSON(), nullable=True),
    sa.Column('total_requests_made', sa.Integer(), nullable=True),
    sa.Column('requests_per_second', sa.Float(), nullable=True),
    sa.Column('latency_min', sa.Float(), nullable=True),
    sa.Column('latency_max', sa.Float(), nullable=True),
    sa.Column('latency_avg', sa.Float(), nullable=True),
    sa.Column('latency_p50', sa.Float(), nullable=True),
    sa.Column('latency_p75', sa.Float(), nullable=True),
    sa.Column('latency_p90', sa.Float(), nullable=True),
    sa.Column('latency_p95', sa.Float(), nullable=True),
    sa.Column('latency_p99', sa.Float(), nullable=True),
    sa.Column('data_received_bytes', sa.Integer(), nullable=True),
    sa.Column('data_sent_bytes', sa.Integer(), nullable=True),
    sa.Column('throughput_bytes_per_second', sa.Float(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('error_rate', sa.Float(), nullable=True),
    sa.Column('errors_by_type', sa.JSON(), nullable=True),
    sa.Column('max_virtual_users', sa.Integer(), nullable=True),
    sa.Column('virtual_users_timeline', sa.JSON(), nullable=True),
    sa.Column('latency_timeline', sa.JSON(), nullable=True),
    sa.Column('rps_timeline', sa.JSON(), nullable=True),
    sa.Column('errors_timeline', sa.JSON(), nullable=True),
    sa.Column('waterfall_url', sa.String(length=2000), nullable=True),
    sa.Column('filmstrip_url', sa.String(length=2000), nullable=True),
    sa.Column('screenshot_url', sa.String(length=2000), nullable=True),
    sa.Column('video_url', sa.String(length=2000), nullable=True),
    sa.Column('start_render_ms', sa.Float(), nullable=True),
    sa.Column('visually_complete_ms', sa.Float(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['performance_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_id')
    )
    op.create_table('performance_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('share_token', sa.String(length=100), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['performance_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_table('performance_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('test_type', sa.Enum('lighthouse', 'load', 'stress', 'spike', 'endurance', 'api', name='testtype'), nullable=False),
    sa.Column('target_url', sa.String(length=2000), nullable=False),
    sa.Column('test_config', sa.JSON(), nullable=True),
    sa.Column('frequency', postgresql.ENUM('once', 'hourly', 'daily', 'weekly', 'monthly', 'custom', name='schedulefrequency', create_type=False), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_id', sa.UUID(), nullable=True),
    sa.Column('total_runs', sa.Integer(), nullable=True),
    sa.Column('notify_on_complete', sa.Boolean(), nullable=True),
    sa.Column('notify_on_failure', sa.Boolean(), nullable=True),
    sa.Column('notify_on_threshold_breach', sa.Boolean(), nullable=True),
    sa.Column('notification_emails', sa.JSON(), nullable=True),
    sa.Column('notification_slack_webhook', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_test_id'], ['performance_tests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.Column('human_id', sa.String(length=15), nullable=True),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'queued', 'running', 'completed', 'failed', 'cancelled', name='teststatus'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('latency_p95', sa.Float(), nullable=True),
    sa.Column('requests_per_second', sa.Float(), nullable=True),
    sa.Column('error_rate', sa.Float(), nullable=True),
    sa.Column('threshold_passed', sa.Boolean(), nullable=True),
    sa.Column('threshold_details', sa.JSON(), nullable=True),
    sa.Column('metrics_snapshot', sa.JSON(), nullable=True),
    sa.Column('provider', sa.Enum('pagespeed_insights', 'webpagetest', 'gtmetrix', 'loader_io', 'k6_cloud', 'artillery', name='testprovider'), nullable=True),
    sa.Column('provider_test_id', sa.String(length=255), nullable=True),
    sa.Column('provider_report_url', sa.String(length=2000), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.UUID(), nullable=True),
    sa.Column('trigger_source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['performance_tests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('human_id')
    )
    op.create_index('ix_test_executions_created_at', 'test_executions', ['created_at'], unique=False)
    op.create_index('ix_test_executions_test_id', 'test_executions', ['test_id'], unique=False)
    op.create_table('performance_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'warning', 'info', name='alertseverity'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('actual_value', sa.Float(), nullable=False),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['execution_id'], ['test_executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['performance_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_performance_alerts_project_id', 'performance_alerts', ['project_id'], unique=False)
    op.create_index('ix_performance_alerts_severity', 'performance_alerts', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_performance_alerts_severity', table_name='performance_alerts')
    op.drop_index('ix_performance_alerts_project_id', table_name='performance_alerts')
    op.drop_table('performance_alerts')
    op.drop_index('ix_test_executions_test_id', table_name='test_executions')
    op.drop_index('ix_test_executions_created_at', table_name='test_executions')
    op.drop_table('test_executions')
    op.drop_table('performance_schedules')
    op.drop_table('performance_reports')
    op.drop_table('performance_metrics')
    op.drop_index('ix_performance_tests_test_type', table_name='performance_tests')
    op.drop_index('ix_performance_tests_status', table_name='performance_tests')
    op.drop_index('ix_performance_tests_project_id', table_name='performance_tests')
    op.drop_index('ix_performance_tests_organisation_id', table_name='performance_tests')
    op.drop_index('ix_performance_tests_created_at', table_name='performance_tests')
    op.drop_table('performance_tests')
    # ### end Alembic commands ###
