"""Add automation hub integration tables

Revision ID: c22c105dde5c
Revises: 87e0c3a06ef3
Create Date: 2025-11-16 20:02:12.373723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c22c105dde5c'
down_revision: Union[str, Sequence[str], None] = '87e0c3a06ef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_scripts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('script_type', sa.Enum('web', 'workflow', 'api', 'mobile', name='automationscripttype'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'inactive', 'deprecated', name='automationscriptstatus'), nullable=True),
    sa.Column('script_content', sa.Text(), nullable=True),
    sa.Column('script_path', sa.String(length=1000), nullable=True),
    sa.Column('script_repository', sa.String(length=500), nullable=True),
    sa.Column('execution_environment', sa.String(length=255), nullable=True),
    sa.Column('execution_timeout', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('trigger_parameters', sa.JSON(), nullable=True),
    sa.Column('environment_variables', sa.JSON(), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('prerequisites', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('total_executions', sa.Integer(), nullable=True),
    sa.Column('successful_executions', sa.Integer(), nullable=True),
    sa.Column('failed_executions', sa.Integer(), nullable=True),
    sa.Column('average_duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('last_executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('integration_type', sa.Enum('JIRA', 'GITHUB', 'TESTRAIL', 'GITLAB', 'AZURE_DEVOPS', 'CUSTOM', name='integrationtype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ERROR', 'TESTING', name='integrationstatus'), nullable=True),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('api_token', sa.Text(), nullable=False),
    sa.Column('api_key', sa.String(length=500), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('sync_direction', sa.Enum('ONE_WAY_TO_EXTERNAL', 'ONE_WAY_FROM_EXTERNAL', 'BI_DIRECTIONAL', name='syncdirection'), nullable=True),
    sa.Column('auto_sync_enabled', sa.Boolean(), nullable=True),
    sa.Column('sync_interval_minutes', sa.String(length=50), nullable=True),
    sa.Column('sync_filters', sa.JSON(), nullable=True),
    sa.Column('field_mappings', sa.JSON(), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('webhook_secret', sa.String(length=255), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.String(length=50), nullable=True),
    sa.Column('last_sync_details', sa.JSON(), nullable=True),
    sa.Column('total_synced_items', sa.String(length=50), nullable=True),
    sa.Column('total_sync_errors', sa.String(length=50), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrations_integration_type'), 'integrations', ['integration_type'], unique=False)
    op.create_index(op.f('ix_integrations_name'), 'integrations', ['name'], unique=False)
    op.create_index(op.f('ix_integrations_status'), 'integrations', ['status'], unique=False)
    op.create_table('integration_sync_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('integration_id', sa.UUID(), nullable=False),
    sa.Column('sync_type', sa.String(length=50), nullable=False),
    sa.Column('sync_direction', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('external_entity_id', sa.String(length=255), nullable=True),
    sa.Column('items_processed', sa.String(length=50), nullable=True),
    sa.Column('items_succeeded', sa.String(length=50), nullable=True),
    sa.Column('items_failed', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('duration_seconds', sa.String(length=50), nullable=True),
    sa.Column('sync_data', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triggered_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_sync_logs_status'), 'integration_sync_logs', ['status'], unique=False)
    op.create_table('test_case_execution_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_case_id', sa.UUID(), nullable=False),
    sa.Column('automation_script_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('execution_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'passed', 'failed', 'error', 'skipped', 'cancelled', name='executionstatus'), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('actual_result', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_logs', sa.JSON(), nullable=True),
    sa.Column('console_logs', sa.Text(), nullable=True),
    sa.Column('screenshots', sa.JSON(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_environment', sa.JSON(), nullable=True),
    sa.Column('triggered_by', sa.String(length=255), nullable=True),
    sa.Column('test_data', sa.JSON(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('executed_by', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['automation_script_id'], ['automation_scripts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('idx_memory_images_memory_id', table_name='organisation_memory_images')
    op.drop_index('idx_memory_images_order', table_name='organisation_memory_images')
    op.drop_index('ix_organisation_memory_images_memory_id', table_name='organisation_memory_images')
    op.drop_table('organisation_memory_images')
    op.drop_index('idx_memory_usage_memory_id', table_name='memory_usage_log')
    op.drop_index('idx_memory_usage_org_id', table_name='memory_usage_log')
    op.drop_index('idx_memory_usage_used_at', table_name='memory_usage_log')
    op.drop_index('ix_memory_usage_log_memory_id', table_name='memory_usage_log')
    op.drop_index('ix_memory_usage_log_organisation_id', table_name='memory_usage_log')
    op.drop_index('ix_memory_usage_log_used_at', table_name='memory_usage_log')
    op.drop_table('memory_usage_log')
    op.drop_index('idx_org_memory_active', table_name='organisation_memory')
    op.drop_index('idx_org_memory_created_at', table_name='organisation_memory')
    op.drop_index('idx_org_memory_has_images', table_name='organisation_memory')
    op.drop_index('idx_org_memory_org_id', table_name='organisation_memory')
    op.drop_index('idx_org_memory_project_id', table_name='organisation_memory')
    op.drop_index('ix_organisation_memory_created_at', table_name='organisation_memory')
    op.drop_index('ix_organisation_memory_has_images', table_name='organisation_memory')
    op.drop_index('ix_organisation_memory_input_type', table_name='organisation_memory')
    op.drop_index('ix_organisation_memory_is_active', table_name='organisation_memory')
    op.drop_index('ix_organisation_memory_organisation_id', table_name='organisation_memory')
    op.drop_index('ix_organisation_memory_project_id', table_name='organisation_memory')
    op.drop_index('ix_organisation_memory_source', table_name='organisation_memory')
    op.drop_table('organisation_memory')
    op.add_column('test_cases', sa.Column('automation_script_id', sa.UUID(), nullable=True))
    op.add_column('test_cases', sa.Column('automation_enabled', sa.Boolean(), nullable=True))
    op.add_column('test_cases', sa.Column('automation_metadata', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'test_cases', 'automation_scripts', ['automation_script_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_cases', type_='foreignkey')
    op.drop_column('test_cases', 'automation_metadata')
    op.drop_column('test_cases', 'automation_enabled')
    op.drop_column('test_cases', 'automation_script_id')
    op.create_table('organisation_memory',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('input_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('user_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('processed_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('has_images', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_images', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_analysis', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('extracted_features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ui_elements', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('workflows', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('searchable_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('qdrant_collection', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('qdrant_point_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('times_referenced', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('effectiveness_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('last_referenced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('generated_test_plan_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('generated_test_case_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('meta_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='organisation_memory_created_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name='organisation_memory_organisation_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='organisation_memory_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='organisation_memory_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_organisation_memory_source', 'organisation_memory', ['source'], unique=False)
    op.create_index('ix_organisation_memory_project_id', 'organisation_memory', ['project_id'], unique=False)
    op.create_index('ix_organisation_memory_organisation_id', 'organisation_memory', ['organisation_id'], unique=False)
    op.create_index('ix_organisation_memory_is_active', 'organisation_memory', ['is_active'], unique=False)
    op.create_index('ix_organisation_memory_input_type', 'organisation_memory', ['input_type'], unique=False)
    op.create_index('ix_organisation_memory_has_images', 'organisation_memory', ['has_images'], unique=False)
    op.create_index('ix_organisation_memory_created_at', 'organisation_memory', ['created_at'], unique=False)
    op.create_index('idx_org_memory_project_id', 'organisation_memory', ['project_id'], unique=False)
    op.create_index('idx_org_memory_org_id', 'organisation_memory', ['organisation_id'], unique=False)
    op.create_index('idx_org_memory_has_images', 'organisation_memory', ['has_images'], unique=False)
    op.create_index('idx_org_memory_created_at', 'organisation_memory', ['created_at'], unique=False)
    op.create_index('idx_org_memory_active', 'organisation_memory', ['is_active'], unique=False)
    op.create_table('memory_usage_log',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('memory_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('used_in_generation', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('similarity_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('was_helpful', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('query_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('meta_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['memory_id'], ['organisation_memory.id'], name='memory_usage_log_memory_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name='memory_usage_log_organisation_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='memory_usage_log_pkey')
    )
    op.create_index('ix_memory_usage_log_used_at', 'memory_usage_log', ['used_at'], unique=False)
    op.create_index('ix_memory_usage_log_organisation_id', 'memory_usage_log', ['organisation_id'], unique=False)
    op.create_index('ix_memory_usage_log_memory_id', 'memory_usage_log', ['memory_id'], unique=False)
    op.create_index('idx_memory_usage_used_at', 'memory_usage_log', ['used_at'], unique=False)
    op.create_index('idx_memory_usage_org_id', 'memory_usage_log', ['organisation_id'], unique=False)
    op.create_index('idx_memory_usage_memory_id', 'memory_usage_log', ['memory_id'], unique=False)
    op.create_table('organisation_memory_images',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('memory_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vision_analysis', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('extracted_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('identified_elements', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('image_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('meta_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['memory_id'], ['organisation_memory.id'], name='organisation_memory_images_memory_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='organisation_memory_images_pkey')
    )
    op.create_index('ix_organisation_memory_images_memory_id', 'organisation_memory_images', ['memory_id'], unique=False)
    op.create_index('idx_memory_images_order', 'organisation_memory_images', ['memory_id', 'image_order'], unique=False)
    op.create_index('idx_memory_images_memory_id', 'organisation_memory_images', ['memory_id'], unique=False)
    op.drop_table('test_case_execution_records')
    op.drop_index(op.f('ix_integration_sync_logs_status'), table_name='integration_sync_logs')
    op.drop_table('integration_sync_logs')
    op.drop_index(op.f('ix_integrations_status'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_name'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_integration_type'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_table('automation_scripts')
    # ### end Alembic commands ###
