"""add_performance_test_fields

Revision ID: fe948715253c
Revises: 9f7e8a9b0c1d
Create Date: 2026-01-26 17:59:36.374523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe948715253c'
down_revision: Union[str, Sequence[str], None] = '9f7e8a9b0c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance_metrics', sa.Column('cpu_usage', sa.Float(), nullable=True))
    op.add_column('performance_metrics', sa.Column('memory_usage', sa.Float(), nullable=True))
    op.add_column('performance_metrics', sa.Column('disk_io', sa.Float(), nullable=True))
    op.add_column('performance_metrics', sa.Column('network_io', sa.Float(), nullable=True))
    op.add_column('performance_tests', sa.Column('think_time', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_workflow_schedules_next_run'), 'workflow_schedules', ['next_run_at'], unique=False, postgresql_where='(enabled = true)')
    op.create_index(op.f('ix_workflow_executions_status_running'), 'workflow_executions', ['status'], unique=False, postgresql_where="(status = ANY (ARRAY['pending'::workflowexecutionstatus, 'queued'::workflowexecutionstatus, 'running'::workflowexecutionstatus]))")
    op.alter_column('workflow_executions', 'status',
               existing_type=sa.Enum('pending', 'queued', 'running', 'completed', 'failed', 'stopped', 'waiting', 'timeout', name='executionstatus'),
               type_=postgresql.ENUM('pending', 'queued', 'running', 'completed', 'failed', 'stopped', 'waiting', 'timeout', name='workflowexecutionstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::workflowexecutionstatus"))
    op.alter_column('workflow_execution_steps', 'status',
               existing_type=sa.Enum('pending', 'running', 'completed', 'failed', 'skipped', 'waiting', name='stepstatus'),
               type_=postgresql.ENUM('pending', 'running', 'completed', 'failed', 'skipped', 'waiting', name='workflowstepstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::workflowstepstatus"))
    op.create_index(op.f('ix_workflow_definitions_status_active'), 'workflow_definitions', ['status'], unique=False, postgresql_where="(status = 'active'::workflow_def_status)")
    op.drop_column('workflow_definitions', 'ai_prompt')
    op.drop_column('workflow_definitions', 'ai_generated')
    op.add_column('user_organisations', sa.Column('added_by', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_organisations', type_='foreignkey')
    op.create_foreign_key(op.f('user_organisations_added_by_fkey'), 'user_organisations', 'users', ['added_by'], ['id'], ondelete='SET NULL')
    op.alter_column('user_organisations', 'id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('user_invitations', 'role')
    op.drop_index(op.f('ix_test_suites_numeric_id'), table_name='test_suites')
    op.drop_index(op.f('ix_test_suites_human_id'), table_name='test_suites')
    op.create_index(op.f('ix_test_snippets_project_id'), 'test_snippets', ['project_id'], unique=False)
    op.create_index(op.f('ix_test_snippets_organisation_id'), 'test_snippets', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_test_snippets_name'), 'test_snippets', ['name'], unique=False)
    op.create_index(op.f('ix_test_snippets_is_global'), 'test_snippets', ['is_global'], unique=False)
    op.drop_index(op.f('ix_test_plans_numeric_id'), table_name='test_plans')
    op.drop_index(op.f('ix_test_plans_human_id'), table_name='test_plans')
    op.create_index(op.f('ix_test_flows_project_id'), 'test_flows', ['project_id'], unique=False)
    op.create_index(op.f('ix_test_flows_organisation_id'), 'test_flows', ['organisation_id'], unique=False)
    op.drop_index(op.f('ix_test_cases_numeric_id'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_human_id'), table_name='test_cases')
    op.create_index(op.f('ix_test_artifacts_type'), 'test_artifacts', ['type'], unique=False)
    op.create_index(op.f('ix_test_artifacts_project_id'), 'test_artifacts', ['project_id'], unique=False)
    op.create_index(op.f('ix_test_artifacts_execution_run_id'), 'test_artifacts', ['execution_run_id'], unique=False)
    op.create_index(op.f('ix_test_artifacts_created_at'), 'test_artifacts', ['created_at'], unique=False)
    op.create_index(op.f('ix_subscription_plans_name'), 'subscription_plans', ['name'], unique=False)
    op.create_index(op.f('ix_step_results_execution_run_id'), 'step_results', ['execution_run_id'], unique=False)
    op.drop_column('performance_tests', 'think_time')
    op.drop_column('performance_metrics', 'network_io')
    op.drop_column('performance_metrics', 'disk_io')
    op.drop_column('performance_metrics', 'memory_usage')
    op.drop_column('performance_metrics', 'cpu_usage')
    op.create_index(op.f('ix_organization_subscriptions_status'), 'organization_subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_organization_subscriptions_org_id'), 'organization_subscriptions', ['organisation_id'], unique=False)
    op.alter_column('organization_subscriptions', 'current_period_start',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'organisations', type_='foreignkey')
    op.create_foreign_key(op.f('organisations_owner_id_fkey'), 'organisations', 'users', ['owner_id'], ['id'])
    op.alter_column('organisations', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_locator_alternatives_test_flow_id'), 'locator_alternatives', ['test_flow_id'], unique=False)
    op.create_index(op.f('ix_healing_events_execution_run_id'), 'healing_events', ['execution_run_id'], unique=False)
    op.create_index(op.f('ix_execution_runs_test_flow_id'), 'execution_runs', ['test_flow_id'], unique=False)
    op.drop_constraint(None, 'document_knowledge', type_='foreignkey')
    op.create_foreign_key(op.f('document_knowledge_created_by_fkey'), 'document_knowledge', 'users', ['created_by'], ['id'])
    op.create_index(op.f('ix_api_files_project_id'), 'api_files', ['project_id'], unique=False)
    op.add_column('api_environments', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('api_environments', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'api_environments', type_='foreignkey')
    op.create_foreign_key(op.f('api_environments_created_by_fkey'), 'api_environments', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_api_environments_project_id'), 'api_environments', ['project_id'], unique=False)
    op.add_column('api_collections', sa.Column('source_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('api_collections', sa.Column('imported_from', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'api_collections', type_='foreignkey')
    op.alter_column('api_collections', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'ai_feedback', type_='foreignkey')
    op.create_foreign_key(op.f('ai_feedback_user_id_fkey'), 'ai_feedback', 'users', ['user_id'], ['id'])
    op.create_table('sast_findings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('scan_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('human_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('rule_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('rule_name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('engine', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=2000), autoincrement=False, nullable=False),
    sa.Column('start_line', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('end_line', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_column', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('end_column', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('code_snippet', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fingerprint', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cwe_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('owasp_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('remediation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('references', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ai_fix_suggestion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_explanation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('suppression_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('suppression_expires', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['sast_scans.id'], name=op.f('sast_findings_scan_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sast_findings_pkey')),
    sa.UniqueConstraint('human_id', name=op.f('sast_findings_human_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_sast_findings_severity'), 'sast_findings', ['severity'], unique=False)
    op.create_index(op.f('ix_sast_findings_scan_id'), 'sast_findings', ['scan_id'], unique=False)
    op.create_table('security_policies',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('max_critical', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_high', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_medium', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_low', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fail_on_threshold_breach', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('require_sast_scan', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('require_sca_scan', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('require_secret_scan', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('block_high_risk_licenses', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('allowed_licenses', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('blocked_licenses', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('security_policies_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('security_policies_organisation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('security_policies_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('security_policies_pkey'))
    )
    op.create_index(op.f('ix_security_policies_project_id'), 'security_policies', ['project_id'], unique=False)
    op.create_index(op.f('ix_security_policies_organisation_id'), 'security_policies', ['organisation_id'], unique=False)
    op.create_table('security_tickets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('finding_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('finding_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tracker_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('external_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('external_url', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('external_status', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('sync_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('security_tickets_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('security_tickets_pkey'))
    )
    op.create_index(op.f('ix_security_tickets_project_id'), 'security_tickets', ['project_id'], unique=False)
    op.create_index(op.f('ix_security_tickets_finding_id'), 'security_tickets', ['finding_id'], unique=False)
    op.create_table('rasp_configs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('block_sql_injection', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('block_xss', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('block_command_injection', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('block_path_traversal', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('block_ssrf', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('enable_rate_limiting', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('rate_limit_requests', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rate_limit_window', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('alert_on_block', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('alert_emails', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('webhook_url', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('custom_block_patterns', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('whitelist_ips', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('whitelist_paths', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('rasp_configs_organisation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('rasp_configs_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('rasp_configs_pkey'))
    )
    op.create_index(op.f('ix_rasp_configs_project_id'), 'rasp_configs', ['project_id'], unique=False)
    op.create_table('iast_sessions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('human_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('app_url', sa.VARCHAR(length=2000), autoincrement=False, nullable=False),
    sa.Column('app_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('session_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('detect_sql_injection', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('detect_xss', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('detect_path_traversal', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('detect_command_injection', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('requests_analyzed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vulnerabilities_found', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('iast_sessions_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('iast_sessions_organisation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('iast_sessions_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('iast_sessions_pkey')),
    sa.UniqueConstraint('human_id', name=op.f('iast_sessions_human_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('session_token', name=op.f('iast_sessions_session_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_iast_sessions_project_id'), 'iast_sessions', ['project_id'], unique=False)
    op.create_table('sboms',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('human_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('format', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('spec_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('source_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('source_path', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('total_components', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('direct_dependencies', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transitive_dependencies', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('licenses_identified', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('high_risk_licenses', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vulnerable_components', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('raw_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('sboms_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('sboms_organisation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('sboms_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sboms_pkey')),
    sa.UniqueConstraint('human_id', name=op.f('sboms_human_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_sboms_project_id'), 'sboms', ['project_id'], unique=False)
    op.create_table('human_id_counters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('suite_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('next_number', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('human_id_counters_pkey')),
    sa.UniqueConstraint('entity_type', 'plan_id', name=op.f('uq_hid_counter_suite_per_plan'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('entity_type', 'suite_id', name=op.f('uq_hid_counter_case_per_suite'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('sast_scans',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('security_scan_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('human_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('repo_url', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('repo_branch', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('commit_sha', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('local_path', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('engines', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('languages', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ruleset', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('exclude_patterns', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('total_findings', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('critical_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('high_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('medium_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('low_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('info_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('files_scanned', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lines_scanned', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('sast_scans_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('sast_scans_organisation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('sast_scans_project_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_scan_id'], ['security_scans.id'], name=op.f('sast_scans_security_scan_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sast_scans_pkey')),
    sa.UniqueConstraint('human_id', name=op.f('sast_scans_human_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_sast_scans_status'), 'sast_scans', ['status'], unique=False)
    op.create_index(op.f('ix_sast_scans_project_id'), 'sast_scans', ['project_id'], unique=False)
    op.create_table('iast_findings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vulnerability_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('http_method', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('request_url', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('request_headers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('request_body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('response_status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('response_body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tainted_input', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sink_location', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('data_flow', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('source_file', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('source_line', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_function', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('stack_trace', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('remediation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('test_case_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['iast_sessions.id'], name=op.f('iast_findings_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('iast_findings_pkey'))
    )
    op.create_index(op.f('ix_iast_findings_session_id'), 'iast_findings', ['session_id'], unique=False)
    op.create_table('cicd_pipelines',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('webhook_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('webhook_secret', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('trigger_on_push', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('trigger_on_pr', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('trigger_branches', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('run_sast', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('run_sca', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('run_secrets', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('policy_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('total_runs', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_run_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('cicd_pipelines_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('cicd_pipelines_organisation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['security_policies.id'], name=op.f('cicd_pipelines_policy_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('cicd_pipelines_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('cicd_pipelines_pkey')),
    sa.UniqueConstraint('webhook_token', name=op.f('cicd_pipelines_webhook_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_cicd_pipelines_webhook_token'), 'cicd_pipelines', ['webhook_token'], unique=False)
    op.create_index(op.f('ix_cicd_pipelines_project_id'), 'cicd_pipelines', ['project_id'], unique=False)
    op.create_table('policy_rules',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('policy_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('rule_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('pattern', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('pattern_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('applies_to', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('file_patterns', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('severity_override', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['security_policies.id'], name=op.f('policy_rules_policy_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('policy_rules_pkey'))
    )
    op.create_index(op.f('ix_policy_rules_policy_id'), 'policy_rules', ['policy_id'], unique=False)
    op.create_table('security_reports',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('report_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('format', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('scan_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('date_from', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('date_to', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('security_reports_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('security_reports_organisation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('security_reports_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('security_reports_pkey'))
    )
    op.create_index(op.f('ix_security_reports_project_id'), 'security_reports', ['project_id'], unique=False)
    op.create_table('rasp_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('config_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('attack_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('was_blocked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('source_ip', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('http_method', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('request_path', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('request_headers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('request_body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('attack_payload', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('matched_pattern', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['rasp_configs.id'], name=op.f('rasp_events_config_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('rasp_events_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('rasp_events_pkey'))
    )
    op.create_index(op.f('ix_rasp_events_project_id'), 'rasp_events', ['project_id'], unique=False)
    op.create_index(op.f('ix_rasp_events_occurred_at'), 'rasp_events', ['occurred_at'], unique=False)
    op.create_table('cicd_pipeline_runs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pipeline_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('commit_sha', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('branch', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('pr_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('trigger_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('sast_scan_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('sca_scan_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('gate_passed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('gate_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('sarif_output', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['cicd_pipelines.id'], name=op.f('cicd_pipeline_runs_pipeline_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sast_scan_id'], ['sast_scans.id'], name=op.f('cicd_pipeline_runs_sast_scan_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sca_scan_id'], ['sca_scans.id'], name=op.f('cicd_pipeline_runs_sca_scan_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('cicd_pipeline_runs_pkey'))
    )
    op.create_index(op.f('ix_cicd_pipeline_runs_pipeline_id'), 'cicd_pipeline_runs', ['pipeline_id'], unique=False)
    op.create_table('sca_findings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('scan_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('package_name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('package_version', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('package_ecosystem', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('manifest_file', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('is_vulnerability', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('cve_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ghsa_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('cvss_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cvss_vector', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fixed_version', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('upgrade_path', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_direct', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_license_issue', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('license_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('license_risk', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('references', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['sca_scans.id'], name=op.f('sca_findings_scan_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sca_findings_pkey'))
    )
    op.create_index(op.f('ix_sca_findings_severity'), 'sca_findings', ['severity'], unique=False)
    op.create_index(op.f('ix_sca_findings_scan_id'), 'sca_findings', ['scan_id'], unique=False)
    op.create_table('api_flows',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('nodes_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('edges_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ai_generated', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ai_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('api_flows_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('api_flows_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('api_flows_pkey'))
    )
    op.create_index(op.f('ix_api_flows_project_id'), 'api_flows', ['project_id'], unique=False)
    op.create_table('policy_suppressions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('policy_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('suppression_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('suppression_value', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('file_pattern', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_permanent', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('policy_suppressions_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['policy_id'], ['security_policies.id'], name=op.f('policy_suppressions_policy_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('policy_suppressions_pkey'))
    )
    op.create_table('sca_scans',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('security_scan_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('human_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('manifest_files', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('repo_url', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('engines', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('check_licenses', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('check_vulnerabilities', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('total_dependencies', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vulnerable_dependencies', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('license_issues', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('critical_vulns', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('high_vulns', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('medium_vulns', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('low_vulns', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('sca_scans_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('sca_scans_organisation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('sca_scans_project_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_scan_id'], ['security_scans.id'], name=op.f('sca_scans_security_scan_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sca_scans_pkey')),
    sa.UniqueConstraint('human_id', name=op.f('sca_scans_human_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_sca_scans_project_id'), 'sca_scans', ['project_id'], unique=False)
    op.create_table('sbom_components',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sbom_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('component_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('purl', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('cpe', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('swid', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('ecosystem', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('license_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('license_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('license_risk', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_direct', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('parent_component', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_vulnerable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('vulnerability_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hashes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('external_references', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sbom_id'], ['sboms.id'], name=op.f('sbom_components_sbom_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sbom_components_pkey'))
    )
    op.create_index(op.f('ix_sbom_components_sbom_id'), 'sbom_components', ['sbom_id'], unique=False)
    # ### end Alembic commands ###
